services:

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: chat-database
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
  app:
    build: .
    container_name: chat-server
    env_file:
      - .env
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - database
    restart: unless-stopped
volumes:
  sql_data: