security=Bảo mật

email.send=Đã gửi email đến {0}, vui lòng kiểm tra hộp thư đến

verification.not-exists=Yêu cầu xác thực không tồn tại
verification.expired=Yêu cầu xác thực đã hết hạn
verification.invalid=Yêu cầu xác thực không còn hợp lệ
verification.success=Xác thực thành công
verification.email=Xác thực email
verification.email.verified=Email đã được xác thực
verification.device=Xác thực thiết bị
verification.reset-password=Xác thực thay đổi mật khẩu
verification.used=Yêu cầu này đã được xác thực thành công trước đó

session.verified=Phiên truy cập đã được xác thực