server:
  shutdown: graceful

spring:
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 1m
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${APP_NAME}
    frontend-url: ${FRONTEND_URL}
    backend-url: ${BACKEND_URL}
    app-image: ${FRONTEND_URL}/${APP_ICON}
    unknow-user-url: ${UNKNOW_USER_URL}
  threads:
    virtual:
      enabled: true
  messages:
    basename: messages/profile/profile, messages/authentication/authentication, messages/global/global, messages/authorization/authorization, messages/verification/verification, messages/user/user, messages/conversation/conversation, messages/message/message
    encoding: UTF-8
    fallback-to-system-locale: false
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:publicKey.pem
          private-key-location: classpath:privateKey.pem
          access-token-expire: ${JWT_ACCESS_TOKEN_EXPIRE}
          refresh-token-expire: ${JWT_REFRESH_TOKEN_EXPIRE}
  jackson:
    generator:
      write-numbers-as-strings: true
    default-property-inclusion: non_null
  mail:
    host: ${MAIL_HOST}
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from-name: ${MAIL_FROM_NAME}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: ${MAIL_HOST}
  modulith:
    events:
      completion-mode: delete

app:
  websocket:
    endpoint: "/ws"
    broadcast-path: "/topic"
    user-path: "/queue"
    app-prefixes:
      - "/app"
    user-destination-prefix: "/user"

yitter:
  worker-id: 1
  worker-id-bit-length: 6
  seq-bit-length: 6

cloudflare:
  r2:
    endpoint: ${CLOUDFLARE_R2_ENDPOINT}
    access-key: ${CLOUDFLARE_R2_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_R2_SECRET_KEY}
    bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME}
    bucket-url: ${CLOUDFLARE_R2_BUCKET_URL}

cache:
  expire-after-access:
    message: ${MESSAGE_EXPIRE_AFTER_ACCESS}
    conversation: ${CONVERSATION_EXPIRE_AFTER_ACCESS}
    reactor: ${REACTOR_EXPIRE_AFTER_ACCESS}
    user-presence: ${USER_PRESENCE_EXPIRE_AFTER_ACCESS}

cron-config:
  user:
    cleanup-user-cron: ${CLEANUP_USER_CRON}
    days-to-keep-deleted-user: ${DAYS_TO_KEEP_DELETED_USER}
    unbanned-user-cron: ${UNBANNED_USER_CRON}
  authorization:
    cleanup-role-cron: ${CLEANUP_ROLE_CRON}
    days-to-keep-deleted-role: ${DAYS_TO_KEEP_DELETED_ROLE}
  verification:
    expired-verification-cron: ${EXPIRED_VERIFICATION_CRON}
    cleanup-verification-cron: ${CLEANUP_VERIFICATION_CRON}
    verification-to-keep: ${VERIFICATION_TO_KEEP}
  authentication:
    cleanup-device-cron: ${CLEANUP_DEVICE_CRON}
    revoked-session-expired-cron: ${REVOKED_SESSION_EXPIRED_CRON}
    cleanup-session-cron: ${CLEANUP_SESSION_CRON}
    days-to-keep-session-revoked: ${DAYS_TO_KEEP_SESSION_REVOKED}
  conversation:
    batch-size: ${CONVERSATIONS_BATCH_SIZE}
  message:
    batch-size: ${MESSAGES_BATCH_SIZE}
  reactor:
    batch-size: ${REACTORS_BATCH_SIZE}
