spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: chat
    frontend-url: ${FRONTEND_URL}
    backend-url: ${BACKEND_URL}
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterAccess=900s, maximumSize=1000
  threads:
    virtual:
      enabled: true
  messages:
    basename: messages/profile/profile, messages/authentication/authentication, messages/global/global
    encoding: UTF-8
    fallback-to-system-locale: false
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:publicKey.pem
          private-key-location: classpath:privateKey.pem
          access-token-expire: 300
          refresh-token-expire: 604800
  mail:
    host: ${MAIL_HOST}
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from-name: ${MAIL_FROM_NAME}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: ${MAIL_HOST}
yitter:
  worker-id: 1
  worker-id-bit-length: 6
  seq-bit-length: 6
logging:
  level:
    org.springframework.security: DEBUG
cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}