spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${APP_NAME}
    frontend-url: ${FRONTEND_URL}
    backend-url: ${BACKEND_URL}
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterAccess=900s, maximumSize=1000
  threads:
    virtual:
      enabled: true
  messages:
    basename: messages/profile/profile, messages/authentication/authentication, messages/global/global, messages/authorization/authorization, messages/verification/verification, messages/user/user
    encoding: UTF-8
    fallback-to-system-locale: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 50
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:publicKey.pem
          private-key-location: classpath:privateKey.pem
          access-token-expire: ${JWT_ACCESS_TOKEN_EXPIRE}
          refresh-token-expire: ${JWT_REFRESH_TOKEN_EXPIRE}
  mail:
    host: ${MAIL_HOST}
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from-name: ${MAIL_FROM_NAME}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: ${MAIL_HOST}
app:
  websocket:
    endpoint: "/ws"
    broker-paths:
      - "/topic"
    app-prefixes:
      - "/app"
yitter:
  worker-id: 1
  worker-id-bit-length: 6
  seq-bit-length: 6
logging:
  level:
    org.springframework.security: DEBUG
cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}
cron-config:
  user:
    cleanup-user-cron: ${CLEANUP_USER_CRON}
    days-to-keep-deleted-user: ${DAYS_TO_KEEP_DELETED_USER}
    unbanned-user-cron: ${UNBANNED_USER_CRON}
  authorization:
    cleanup-role-cron: ${CLEANUP_ROLE_CRON}
    days-to-keep-deleted-role: ${DAYS_TO_KEEP_DELETED_ROLE}
  verification:
    expired-verification-cron: ${EXPIRED_VERIFICATION_CRON}
    cleanup-verification-cron: ${CLEANUP_VERIFICATION_CRON}
    verification-to-keep: ${VERIFICATION_TO_KEEP}
  authentication:
    cleanup-device-cron: ${CLEANUP_DEVICE_CRON}
    revoked-session-expired-cron: ${REVOKED_SESSION_EXPIRED_CRON}
    cleanup-session-cron: ${CLEANUP_SESSION_CRON}
    days-to-keep-session-revoked: ${DAYS_TO_KEEP_SESSION_REVOKED}
