spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: ${DEFAULT_BATCH_FETCH_SIZE}
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: ${BATCH_SIZE}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

logging:
  level:
    org.springframework.security: INFO
    social.chat: INFO
