profile.exists=Trang cá nhân đã tồn tại
profile.not-exists=Trang cá nhân không tồn tại
profile.username-exists=Biệt danh {0} đã tồn tại

email.exists=Email đã tồn tại
email.not-exists=Email không tồn tại
email.verified=Email đã được xác thực
email.only-one=Hiện tại chỉ có 1 email duy nhất cho tài khoản này

validation.username.invalid=Biệt danh không hợp lệ
validation.full-name.invalid=Tên đầy đủ không hợp lệ