validation.email.not-blank=Email không được bỏ trống
validation.email.invalid=Email không hợp lệ
validation.password.invalid=Mật khẩu không hợp lệ
validation.password.incorrect=Mật khẩu không đúng

session.not-exists=Phiên truy cập không tồn tại
session.expired=Phiên đăng nhập đã hết hạn

oauth2.email.not-found=Tài khoản của bạn có vẻ chưa liên kết với email hoặc email đã bị ẩn đi. Vui lòng liên kết với email hoặc cấp phép cho nó hiển thị

notification.need-enable=Bạn cần cấp quyền thông báo để nhận thông báo