validation.email.not-blank=Email không được bỏ trống
validation.email.invalid=Email không hợp lệ
validation.password.invalid=Mật khẩu không hợp lệ
validation.password.incorrect=Mật khẩu không đúng

session.not-exists=Phiên truy cập không tồn tại
session.expired=Phiên đăng nhập đã hết hạn