user.error.exists=Người dùng đã tồn tại
user.error.not-exists=Người dùng không tồn tại
user.error.not-verified=Người dùng chưa được xác minh

email.success.send=Đã gửi email, vui lòng kiểm tra hộp thư đến
email.verified=Xác thực email
email.error.verified=Email đã được xác thực

security=Bảo mật