user.exists=Người dùng đã tồn tại
user.not-exists=Người dùng không tồn tại
user.not-verified=Người dùng chưa được xác minh

account.locked=Tài khoản của bạn đã bị khoá
account.inactive=Tài khoản của bạn chưa được kích hoạt
account.invalid=Trạng thái tài khoản không hợp lệ
account.banned=Tài khoản của bạn đã bị cấm cho đến {0}
account.time-banned-invalid=Thời gian cấm cho tài khoản {0} không hợp lệ