global.error.internal=Lỗi hệ thống
global.error.data.invalid=Dữ liệu không hợp lệ
global.error.token.invalid=Khoá không hợp lệ
global.error.forbidden=Bạn không đủ quyển truy cập

global.success.created=Tạo mới dữ liệu thành công
global.success.updated=Cập nhật dữ liệu thành công
global.success.deleted=Xoá dữ liệu thành công
global.success.get=Lấy dữ liệu thành công

global.time.minute=phút
global.time.hour=giờ