user.exists=Người dùng đã tồn tại
user.not-exists=Người dùng không tồn tại
user.not-verified=Người dùng chưa được xác minh

role.exists=Chức vụ đã tồn tại
role.not-exists=Chức vụ không tồn tại
role.default.cant-remove=Chức vụ {0} là mặc định không thể xoá
role.permission-invalid=Quyền cho chức vụ không hợp lệ
role.permission-exists=Quyền cho chức vụ này đã tồn tại

account.blocked=Tài khoản của bạn đã bị khoá
account.inactive=Tài khoản của bạn chưa được kích hoạt
account.invalid=Tài khoản không hợp lệ